on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
      - name: webpack
        run: |
          npm install
          npx webpack
      - name: create GitHub release
        run: |
          zip $ZIP_FILE dist/*
          gh release create v${{ steps.get_version.outputs.VERSION }} $ZIP_FILE
        env:
          ZIP_FILE: following-directions-${{ steps.get_version.outputs.VERSION }}.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
